name: Build docker image
on:  
  push:
  pull_request:
    branches:
      - main
jobs:
    Build:
        runs-on: ubuntu-latest
        env:
            BUILD_IMAGE: bedasoftware/ucfwealth-aidbox-app:latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1
            - run: docker run --rm --privileged tonistiigi/binfmt --install all
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}
            - run: >-
                  docker buildx build
                  --platform linux/arm64,linux/amd64
                  --push
                  --tag ${{ env.BUILD_IMAGE }}
                  .
